package remapped;

import org.lwjgl.opengl.ARBShaderObjects;

public class class_2964 {
   public int field_14523;
   public int field_14494;
   public int field_14498;
   public int field_14488;
   public int field_14508;
   public int field_14496;
   public int field_14530;
   public int field_14471;
   public int field_14513;
   public int field_14532;
   public int field_14515;
   public int field_14491;
   public int field_14507;
   public int field_14514;
   public int field_14497;
   public int field_14475;
   public int field_14539;
   public int field_14521;
   public int field_14525;
   public int field_14531;
   public int field_14528;
   public int field_14487;
   public int field_14510;
   public int field_14493;
   public int field_14537;
   public int field_14482;
   public int field_14489;
   public int field_14504;
   public int field_14501;
   public int field_14538;
   public int field_14511;
   public int field_14535;
   public int field_14536;
   public int field_14484;
   public int field_14500;
   public int field_14480;
   public int field_14483;
   public int field_14512;
   public int field_14466;
   public int field_14495;
   public int field_14533;
   public int field_14467;
   public int field_14490;
   public int field_14506;
   public int field_14517;
   public int field_14492;
   public int field_14527;
   public int field_14477;
   public int field_14465;
   public int field_14505;
   public int field_14529;
   public int field_14469;
   public int field_14470;
   public int field_14509;
   public int field_14468;
   public int field_14502;
   public int field_14479;
   public int field_14503;
   public int field_14534;
   public int field_14464;
   public int field_14526;
   public int field_14476;
   public int field_14472;
   public int field_14473;
   public int field_14485;
   public int field_14518;
   public int field_14486;
   public int field_14524;
   public int field_14519;
   public int field_14499;
   public int field_14474;
   public int field_14516;
   public int field_14520;
   public int field_14522;
   public int field_14478;

   public class_2964(int var1) {
      this.field_14523 = var1;
      this.field_14494 = ARBShaderObjects.glGetUniformLocationARB(var1, "texture");
      this.field_14498 = ARBShaderObjects.glGetUniformLocationARB(var1, "lightmap");
      this.field_14488 = ARBShaderObjects.glGetUniformLocationARB(var1, "normals");
      this.field_14508 = ARBShaderObjects.glGetUniformLocationARB(var1, "specular");
      this.field_14496 = ARBShaderObjects.glGetUniformLocationARB(var1, "shadow");
      this.field_14530 = ARBShaderObjects.glGetUniformLocationARB(var1, "watershadow");
      this.field_14471 = ARBShaderObjects.glGetUniformLocationARB(var1, "shadowtex0");
      this.field_14513 = ARBShaderObjects.glGetUniformLocationARB(var1, "shadowtex1");
      this.field_14532 = ARBShaderObjects.glGetUniformLocationARB(var1, "depthtex0");
      this.field_14515 = ARBShaderObjects.glGetUniformLocationARB(var1, "depthtex1");
      this.field_14491 = ARBShaderObjects.glGetUniformLocationARB(var1, "shadowcolor");
      this.field_14507 = ARBShaderObjects.glGetUniformLocationARB(var1, "shadowcolor0");
      this.field_14514 = ARBShaderObjects.glGetUniformLocationARB(var1, "shadowcolor1");
      this.field_14497 = ARBShaderObjects.glGetUniformLocationARB(var1, "noisetex");
      this.field_14475 = ARBShaderObjects.glGetUniformLocationARB(var1, "gcolor");
      this.field_14539 = ARBShaderObjects.glGetUniformLocationARB(var1, "gdepth");
      this.field_14521 = ARBShaderObjects.glGetUniformLocationARB(var1, "gnormal");
      this.field_14525 = ARBShaderObjects.glGetUniformLocationARB(var1, "composite");
      this.field_14531 = ARBShaderObjects.glGetUniformLocationARB(var1, "gaux1");
      this.field_14528 = ARBShaderObjects.glGetUniformLocationARB(var1, "gaux2");
      this.field_14487 = ARBShaderObjects.glGetUniformLocationARB(var1, "gaux3");
      this.field_14510 = ARBShaderObjects.glGetUniformLocationARB(var1, "gaux4");
      this.field_14493 = ARBShaderObjects.glGetUniformLocationARB(var1, "colortex0");
      this.field_14537 = ARBShaderObjects.glGetUniformLocationARB(var1, "colortex1");
      this.field_14482 = ARBShaderObjects.glGetUniformLocationARB(var1, "colortex2");
      this.field_14489 = ARBShaderObjects.glGetUniformLocationARB(var1, "colortex3");
      this.field_14504 = ARBShaderObjects.glGetUniformLocationARB(var1, "colortex4");
      this.field_14501 = ARBShaderObjects.glGetUniformLocationARB(var1, "colortex5");
      this.field_14538 = ARBShaderObjects.glGetUniformLocationARB(var1, "colortex6");
      this.field_14511 = ARBShaderObjects.glGetUniformLocationARB(var1, "colortex7");
      this.field_14535 = ARBShaderObjects.glGetUniformLocationARB(var1, "gdepthtex");
      this.field_14536 = ARBShaderObjects.glGetUniformLocationARB(var1, "depthtex2");
      this.field_14484 = ARBShaderObjects.glGetUniformLocationARB(var1, "tex");
      this.field_14500 = ARBShaderObjects.glGetUniformLocationARB(var1, "heldItemId");
      this.field_14480 = ARBShaderObjects.glGetUniformLocationARB(var1, "heldBlockLightValue");
      this.field_14483 = ARBShaderObjects.glGetUniformLocationARB(var1, "fogMode");
      this.field_14512 = ARBShaderObjects.glGetUniformLocationARB(var1, "fogColor");
      this.field_14466 = ARBShaderObjects.glGetUniformLocationARB(var1, "skyColor");
      this.field_14495 = ARBShaderObjects.glGetUniformLocationARB(var1, "worldTime");
      this.field_14533 = ARBShaderObjects.glGetUniformLocationARB(var1, "moonPhase");
      this.field_14467 = ARBShaderObjects.glGetUniformLocationARB(var1, "frameTimeCounter");
      this.field_14490 = ARBShaderObjects.glGetUniformLocationARB(var1, "sunAngle");
      this.field_14506 = ARBShaderObjects.glGetUniformLocationARB(var1, "shadowAngle");
      this.field_14517 = ARBShaderObjects.glGetUniformLocationARB(var1, "rainStrength");
      this.field_14492 = ARBShaderObjects.glGetUniformLocationARB(var1, "aspectRatio");
      this.field_14527 = ARBShaderObjects.glGetUniformLocationARB(var1, "viewWidth");
      this.field_14477 = ARBShaderObjects.glGetUniformLocationARB(var1, "viewHeight");
      this.field_14465 = ARBShaderObjects.glGetUniformLocationARB(var1, "near");
      this.field_14505 = ARBShaderObjects.glGetUniformLocationARB(var1, "far");
      this.field_14529 = ARBShaderObjects.glGetUniformLocationARB(var1, "sunPosition");
      this.field_14469 = ARBShaderObjects.glGetUniformLocationARB(var1, "moonPosition");
      this.field_14470 = ARBShaderObjects.glGetUniformLocationARB(var1, "upPosition");
      this.field_14509 = ARBShaderObjects.glGetUniformLocationARB(var1, "previousCameraPosition");
      this.field_14468 = ARBShaderObjects.glGetUniformLocationARB(var1, "cameraPosition");
      this.field_14502 = ARBShaderObjects.glGetUniformLocationARB(var1, "gbufferModelView");
      this.field_14479 = ARBShaderObjects.glGetUniformLocationARB(var1, "gbufferModelViewInverse");
      this.field_14503 = ARBShaderObjects.glGetUniformLocationARB(var1, "gbufferPreviousProjection");
      this.field_14534 = ARBShaderObjects.glGetUniformLocationARB(var1, "gbufferProjection");
      this.field_14464 = ARBShaderObjects.glGetUniformLocationARB(var1, "gbufferProjectionInverse");
      this.field_14526 = ARBShaderObjects.glGetUniformLocationARB(var1, "gbufferPreviousModelView");
      this.field_14476 = ARBShaderObjects.glGetUniformLocationARB(var1, "shadowProjection");
      this.field_14472 = ARBShaderObjects.glGetUniformLocationARB(var1, "shadowProjectionInverse");
      this.field_14473 = ARBShaderObjects.glGetUniformLocationARB(var1, "shadowModelView");
      this.field_14485 = ARBShaderObjects.glGetUniformLocationARB(var1, "shadowModelViewInverse");
      this.field_14518 = ARBShaderObjects.glGetUniformLocationARB(var1, "wetness");
      this.field_14486 = ARBShaderObjects.glGetUniformLocationARB(var1, "eyeAltitude");
      this.field_14524 = ARBShaderObjects.glGetUniformLocationARB(var1, "eyeBrightness");
      this.field_14519 = ARBShaderObjects.glGetUniformLocationARB(var1, "eyeBrightnessSmooth");
      this.field_14499 = ARBShaderObjects.glGetUniformLocationARB(var1, "terrainTextureSize");
      this.field_14474 = ARBShaderObjects.glGetUniformLocationARB(var1, "terrainIconSize");
      this.field_14516 = ARBShaderObjects.glGetUniformLocationARB(var1, "isEyeInWater");
      this.field_14520 = ARBShaderObjects.glGetUniformLocationARB(var1, "hideGUI");
      this.field_14522 = ARBShaderObjects.glGetUniformLocationARB(var1, "centerDepthSmooth");
      this.field_14478 = ARBShaderObjects.glGetUniformLocationARB(var1, "atlasSize");
   }
}
