package remapped;

import java.util.Locale;
import java.util.MissingResourceException;
import java.util.ResourceBundle;

public enum class_1023 implements class_5500 {
   field_5366("Argument {0} outside domain [{1} ; {2}]"),
   field_5645("array size cannot be greater than {0}"),
   field_5488("array sizes should have difference 1 ({0} != {1} + 1)"),
   field_5573("array sums to zero"),
   field_5501("eigen decomposition of assymetric matrices not supported yet"),
   field_5660("matrix must have at least one column"),
   field_5633("matrix must have at least one row"),
   field_5568("bandwidth ({0})"),
   field_5436("Bessel function of order {0} cannot be computed for x = {1}"),
   field_5613("Bessel function of order {0} failed to converge for x = {1}"),
   field_5582("must have n >= k for binomial coefficient (n, k), got k = {0}, n = {1}"),
   field_5635("must have n >= 0 for binomial coefficient (n, k), got n = {0}"),
   field_5599("statistics constructed from external moments cannot be cleared"),
   field_5447("cannot compute 0-th root of unity, indefinite result"),
   field_5362("cannot compute beta density at 0 when alpha = {0,number}"),
   field_5461("cannot compute beta density at 1 when beta = %.3g"),
   field_5607("cannot compute nth root for null or negative n: {0}"),
   field_5513("cannot discard a negative number of elements ({0})"),
   field_5482("cannot format a {0} instance as a 3D vector"),
   field_5539("cannot format a {0} instance as a complex number"),
   field_5606("cannot format a {0} instance as a real vector"),
   field_5560("cannot format given object as a fraction number"),
   field_5466("statistics constructed from external moments cannot be incremented"),
   field_5584("cannot normalize a zero norm vector"),
   field_5614("elements cannot be retrieved from a negative array index {0}"),
   field_5410("cannot set an element at a negative index {0}"),
   field_5604("cannot substitute an element from an empty array"),
   field_5398("Conversion Exception in Transformation: {0}"),
   field_5414("Cardan angles singularity"),
   field_5487("class ({0}) does not implement Comparable"),
   field_5593("too close vertices near point ({0}, {1}, {2})"),
   field_5478("the closest orthogonal matrix has a negative determinant {0}"),
   field_5374("column index {0} out of allowed range [{1}, {2}]"),
   field_5661("column index ({0})"),
   field_5473("constraint"),
   field_5412("Continued fraction convergents diverged to +/- infinity for value {0}"),
   field_5545("Continued fraction diverged to NaN for value {0}"),
   field_5475(
      "contraction criteria ({0}) smaller than the expansion factor ({1}).  This would lead to a never ending loop of expansion and contraction as a newly expanded internal storage array would immediately satisfy the criteria for contraction."
   ),
   field_5643(
      "contraction criteria smaller than one ({0}).  This would lead to a never ending loop of expansion and contraction as an internal storage array length equal to the number of elements would satisfy the contraction criteria."
   ),
   field_5376("convergence failed"),
   field_5393("some outline boundary loops cross each other"),
   field_5427("crossover rate ({0})"),
   field_5563("Cumulative probability function returned NaN for argument {0} p = {1}"),
   field_5372("some rows have length {0} while others have length {1}"),
   field_5548("original and permuted data must contain the same elements"),
   field_5357("digest not initialized"),
   field_5541("got {0}x{1} but expected {2}x{3}"),
   field_5564("{0} != {1}"),
   field_5536("dimensions mismatch"),
   field_5342("Discrete cumulative probability function returned NaN for argument {0}"),
   field_5390("distribution not loaded"),
   field_5426("duplicated abscissa {0} causes division by zero"),
   field_5354("edge joining points ({0}, {1}, {2}) and ({3}, {4}, {5}) is connected to one facet only"),
   field_5629("elitism rate ({0})"),
   field_5605("empty cluster in k-means"),
   field_5402("sample for interpolation is empty"),
   field_5485("empty polynomials coefficients array"),
   field_5515("empty selected column index array"),
   field_5518("empty selected row index array"),
   field_5588("empty string for imaginary character"),
   field_5543("endpoints do not specify an interval: [{0}, {1}]"),
   field_5437("equal vertices {0} and {1} in simplex configuration"),
   field_5577("Euler angles singularity"),
   field_5514("evaluation"),
   field_5353("expansion factor smaller than one ({0})"),
   field_5370("facets orientation mismatch around edge joining points ({0}, {1}, {2}) and ({3}, {4}, {5})"),
   field_5496("must have n >= 0 for n!, got n = {0}"),
   field_5667(
      "number of iterations={4}, maximum iterations={5}, initial={6}, lower bound={7}, upper bound={8}, final a value={0}, final b value={1}, f(a)={2}, f(b)={3}"
   ),
   field_5648("Unable to convert {0} to fraction after {1} iterations"),
   field_5572("first {0} columns are not initialized yet"),
   field_5360("first element is not 0: {0}"),
   field_5656("first {0} rows are not initialized yet"),
   field_5424("Overflow trying to convert {0} to fraction ({1}/{2})"),
   field_5417("function is not differentiable"),
   field_5553("function is not polynomial"),
   field_5359("overflow: gcd({0}, {1}) is 2^31"),
   field_5358("overflow: gcd({0}, {1}) is 2^63"),
   field_5476("{0} wide hole between models time ranges"),
   field_5341("condition number {1} is too high "),
   field_5415("inconsistent state at 2π wrapping"),
   field_5623("the index specified: {0} is larger than the current maximal index {1}"),
   field_5608("index ({0}) is not positive"),
   field_5408("index {0} out of allowed range [{1}, {2}]"),
   field_5452("index ({0})"),
   field_5534("{0} is not a finite number"),
   field_5641("interval bounds must be finite"),
   field_5502("value {0} at index {1}"),
   field_5657("Array contains an infinite element, {0} at index {1}"),
   field_5557("cannot convert infinite value"),
   field_5349("initial capacity ({0}) is not positive"),
   field_5480("initial column {1} after final column {0}"),
   field_5506("initial row {1} after final row {0}"),
   /** @deprecated */
   field_5559("input data comes from unsupported datasource: {0}, supported sources: {1}, {2}"),
   field_5535("instance of class {0} not comparable to existing values"),
   field_5547("insufficient data"),
   field_5471("insufficient data for t statistic, needs at least 2, got {0}"),
   field_5400("insufficient dimension {0}, must be at least {1}"),
   field_5456("dimension ({0})"),
   field_5421("sample contains {0} observed points, at least {1} are required"),
   field_5508("insufficient data: only {0} rows and {1} columns."),
   field_5479("multistep method needs at least {0} previous steps, got {1}"),
   field_5650("internal error, please fill a bug report at {0}"),
   field_5470("invalid binary digit: {0}"),
   field_5455("binary mutation works on BinaryChromosome only"),
   field_5602("invalid bracketing parameters:  lower bound={0},  initial={1}, upper bound={2}"),
   field_5409("one-point crossover only works with fixed-length chromosomes"),
   field_5575("required functionality is missing in {0}"),
   field_5586("invalid interval, initial value parameters:  lower={0}, initial={1}, upper={2}"),
   field_5618("invalid iteration limits: min={0}, max={1}"),
   field_5385("bad value for maximum iterations number: {0}"),
   field_5640("the number of observations is not sufficient to conduct regression"),
   field_5651("input data array length = {0} does not match the number of observations = {1} and the number of regressors = {2}"),
   field_5591("length of regressor array = {0} does not match the number of variables = {1} in the model"),
   field_5550("invalid rounding method {0}, valid methods: {1} ({2}), {3} ({4}), {5} ({6}), {7} ({8}), {9} ({10}), {11} ({12}), {13} ({14}), {15} ({16})"),
   field_5621("iterator exhausted"),
   field_5503("iterations"),
   field_5356("overflow: lcm({0}, {1}) is 2^31"),
   field_5666("overflow: lcm({0}, {1}) is 2^63"),
   field_5468("list of chromosomes bigger than maxPopulationSize"),
   field_5441("Loess expects at least 1 point"),
   field_5386("lower bound ({0}) must be strictly less than upper bound ({1})"),
   field_5383("lower endpoint ({0}) must be less than or equal to upper endpoint ({1})"),
   field_5460("map has been modified while iterating"),
   field_5609("evaluations"),
   field_5587("maximal count ({0}) exceeded"),
   field_5492("maximal number of iterations ({0}) exceeded"),
   field_5453("minimal step size ({1,number,0.00E00}) reached, integration needs {0,number,0.00E00}"),
   field_5571("Loess expects the abscissa and ordinate arrays to be of the same size, but got {0} abscissae and {1} ordinatae"),
   field_5517("mutation rate ({0})"),
   field_5505("element {0} is NaN"),
   field_5472("cannot convert NaN value"),
   field_5659("brightness exponent should be positive or null, but got {0}"),
   field_5448("negative complex module {0}"),
   field_5495("element ({0}, {1}) is negative: {2}"),
   field_5576("element {0} is negative: {1}"),
   field_5512("number of successes must be non-negative ({0})"),
   field_5499("number of successes ({0})"),
   field_5493("number of trials must be non-negative ({0})"),
   field_5664("number of interpolation points ({0})"),
   field_5355("number of trials ({0})"),
   field_5435("vertices do not form a convex hull in CCW winding"),
   field_5481("number of robustness iterations ({0})"),
   field_5616("start position ({0})"),
   field_5367("Continued fraction convergents failed to converge (in less than {0} iterations) for value {1}"),
   field_5625("non-invertible affine transform collapses some lines into single points"),
   field_5589("number of microsphere elements must be positive, but got {0}"),
   field_5592("polynomial degree must be positive: degree={0}"),
   field_5551("all abscissae must be finite real numbers, but {0}-th is {1}"),
   field_5619("all ordinatae must be finite real numbers, but {0}-th is {1}"),
   field_5420("all weights must be finite real numbers, but {0}-th is {1}"),
   field_5429("non square ({0}x{1}) matrix"),
   field_5611("Norm ({0})"),
   field_5561("Cannot normalize to an infinite value"),
   field_5532("Cannot normalize to NaN"),
   field_5449("{0}x{1} and {2}x{3} matrices are not addition compatible"),
   field_5434("points {0} and {1} are not decreasing ({2} < {3})"),
   field_5528("points {3} and {2} are not decreasing ({1} < {0})"),
   field_5523("not enough data ({0} rows) for this many predictors ({1} predictors)"),
   field_5442("spline partition must have at least {0} points, got {1}"),
   field_5463("points {0} and {1} are not increasing ({2} > {3})"),
   field_5388("points {3} and {2} are not increasing ({1} > {0})"),
   field_5395("{0}x{1} and {2}x{3} matrices are not multiplication compatible"),
   field_5654("not positive definite matrix"),
   field_5439("not positive definite matrix: diagonal element at ({1},{1}) is smaller than {2} ({0})"),
   field_5431("non positive definite linear operator"),
   field_5530("non self-adjoint linear operator"),
   field_5598("non square ({0}x{1}) linear operator"),
   field_5343("degrees of freedom ({0})"),
   field_5484("degrees of freedom must be positive ({0})"),
   field_5407("element {0} is not positive: {1}"),
   field_5404("invalid exponent {0} (must be positive)"),
   field_5510("number of elements should be positive ({0})"),
   field_5474("base ({0})"),
   field_5583("exponent ({0})"),
   field_5389("length must be positive ({0})"),
   field_5544("length ({0})"),
   field_5458("mean must be positive ({0})"),
   field_5630("mean ({0})"),
   field_5396("number of sample is not positive: {0}"),
   field_5405("number of samples ({0})"),
   field_5464("permutation k ({0}) must be positive"),
   field_5384("permutation size ({0}"),
   field_5377("the Poisson mean must be positive ({0})"),
   field_5620("population size must be positive ({0})"),
   field_5373("population size ({0})"),
   field_5516("invalid row dimension: {0} (must be positive)"),
   field_5451("sample size must be positive ({0})"),
   field_5422("scale must be positive ({0})"),
   field_5477("scale ({0})"),
   field_5669("shape must be positive ({0})"),
   field_5567("shape ({0})"),
   field_5399("standard deviation must be positive ({0})"),
   field_5525("standard deviation ({0})"),
   field_5617("upper bound must be positive ({0})"),
   field_5432("window size must be positive ({0})"),
   field_5344("{0} is not a power of 2"),
   field_5403("{0} is not a power of 2, consider padding for fix"),
   field_5594("{0} is not a power of 2 plus one"),
   field_5379("points {0} and {1} are not strictly decreasing ({2} <= {3})"),
   field_5387("points {3} and {2} are not strictly decreasing ({1} <= {0})"),
   field_5570("knot values must be strictly increasing"),
   field_5540("points {0} and {1} are not strictly increasing ({2} >= {3})"),
   field_5392("points {3} and {2} are not strictly increasing ({1} >= {0})"),
   field_5494("{0}x{1} and {2}x{3} matrices are not subtraction compatible"),
   field_5668("method not supported in dimension {0}"),
   field_5419("not symmetric matrix"),
   field_5469("non symmetric matrix: the difference between entries at ({0},{1}) and ({1},{0}) is larger than {2}"),
   field_5652("no bin selected"),
   field_5653("none of the {0} start points lead to convergence"),
   field_5519("no data"),
   field_5433("no degrees of freedom ({0} measurements, {1} parameters)"),
   field_5347("This distribution does not have a density function implemented"),
   field_5423("no feasible solution"),
   field_5445("no optimum computed yet"),
   field_5549("Regression model must include at least one regressor"),
   field_5365("no result available"),
   field_5574("no entry at indices ({0}, {1}) in a {2}x{3} matrix"),
   field_5371("NaN is not allowed"),
   field_5537("null is not allowed"),
   field_5600("a null or zero length array not allowed"),
   field_5500("covariance matrix"),
   field_5497("denominator"),
   field_5634("denominator format"),
   field_5428("fraction"),
   field_5581("function"),
   field_5637("imaginary format"),
   field_5401("input array"),
   field_5438("numerator"),
   field_5459("numerator format"),
   field_5655("conversion exception in transformation"),
   field_5580("real format"),
   field_5610("whole format"),
   field_5491("{0} is larger than the maximum ({1})"),
   field_5368("{0} is smaller than the minimum ({1})"),
   field_5622("{0} is larger than, or equal to, the maximum ({1})"),
   field_5663("{0} is smaller than, or equal to, the minimum ({1})"),
   field_5542("number of successes ({0}) must be less than or equal to population size ({1})"),
   field_5380("overflow, numerator too large after multiply: {0}"),
   field_5444("{0} points Legendre-Gauss integrator not supported, number of points must be in the {1}-{2} range"),
   field_5381("observed counts are all 0 in observed array {0}"),
   field_5636("observed counts are both zero for entry {0}"),
   field_5662("the difference between the upper and lower bound must be larger than twice the initial trust region radius ({0})"),
   field_5440("out of bounds quantile value: {0}, must be in (0, 100]"),
   field_5450("out of bounds confidence level {0}, must be between {1} and {2}"),
   field_5638("out of bounds significance level {0}, must be between {1} and {2}"),
   field_5369("significance level ({0})"),
   field_5558("the abscissae array must be sorted in a strictly increasing order, but the {0}-th element is {1} whereas {2}-th is {3}"),
   field_5382("point ({0}, {1}, {2}) is out of plane"),
   field_5486("out of range root of unity index {0} (must be in [{1};{2}])"),
   field_5352("out of range"),
   field_5647("{0} out of [{1}, {2}] range"),
   field_5425("{0} out of ({1}, {2}] range"),
   field_5626("{0} out of [{1}, {2}) range"),
   field_5579("an outline boundary loop is open"),
   field_5596("overflow"),
   field_5375("overflow in fraction {0}/{1}, cannot negate"),
   field_5524("overflow in addition: {0} + {1}"),
   field_5406("overflow in subtraction: {0} - {1}"),
   field_5454("overflow in multiplication: {0} * {1}"),
   field_5631("cannot access {0} method in percentile implementation {1}"),
   field_5507("percentile implementation {0} does not support {1}"),
   field_5345("permutation size ({0}) exceeds permuation domain ({1})"),
   field_5590("polynomial"),
   field_5624("number of polynomial interpolants must match the number of segments ({0} != {1} - 1)"),
   field_5632("population limit has to be positive"),
   field_5601("cannot raise an integral value to a negative power ({0}^{1})"),
   field_5555("propagation direction mismatch"),
   field_5397("RandomKeyMutation works only with RandomKeys, not {0}"),
   field_5533("roots of unity have not been computed yet"),
   field_5465("a {0}x{1} matrix cannot be a rotation matrix"),
   field_5578("row index {0} out of allowed range [{1}, {2}]"),
   field_5569("row index ({0})"),
   field_5646("function values at endpoints do not have different signs, endpoints: [{0}, {1}], values: [{2}, {3}]"),
   field_5665("sample size ({0}) exceeds collection size ({1})"),
   field_5565("sample size ({0}) must be less than or equal to population size ({1})"),
   field_5446("simplex must contain at least one point"),
   field_5603("{0}"),
   field_5467("matrix is singular"),
   field_5498("operator is singular"),
   field_5350("subarray ends after array end"),
   field_5413("cutoff singular value is {0}, should be at most {1}"),
   field_5552("tournament arity ({0}) cannot be bigger than population size ({1})"),
   field_5529("cannot discard {0} elements from a {1} elements array"),
   field_5394("too many regressors ({0}) specified, only {1} in the model"),
   field_5511("cost relative tolerance is too small ({0}), no further reduction in the sum of squares is possible"),
   field_5490("too small integration interval: length = {0}"),
   field_5462("orthogonality tolerance is too small ({0}), solution is orthogonal to the jacobian"),
   field_5585("parameters relative tolerance is too small ({0}), no further improvement in the approximate solution is possible"),
   field_5628("trust region step has failed to reduce Q"),
   field_5457("two or more categories required, got {0}"),
   field_5348("two or more values required in each category, one has {0}"),
   field_5418("unable to bracket optimum in line search"),
   field_5411("unable to compute covariances: singular problem"),
   field_5658("unable to first guess the harmonic coefficients"),
   field_5504("unable to orthogonalize matrix in {0} iterations"),
   field_5521("unable to perform Q.R decomposition on the {0}x{1} jacobian matrix"),
   field_5615("unable to solve: singular problem"),
   field_5554("unbounded solution"),
   field_5546("unknown mode {0}, known modes: {1} ({2}), {3} ({4}), {5} ({6}), {7} ({8}), {9} ({10}) and {11} ({12})"),
   field_5642("unknown parameter {0}"),
   field_5526("ode does not match the main ode set in the extended set"),
   field_5509("string \"{0}\" unparseable (from position {1}) as an object of type {2}"),
   field_5483("string \"{0}\" unparseable (from position {1})"),
   field_5378("unparseable 3D vector: \"{0}\""),
   field_5649("unparseable complex number: \"{0}\""),
   field_5522("unparseable real vector: \"{0}\""),
   field_5644("unsupported expansion mode {0}, supported modes are {1} ({2}) and {3} ({4})"),
   field_5351("unsupported operation"),
   field_5489("arithmetic exception"),
   field_5346("illegal state"),
   field_5416("exception generated in user code"),
   field_5527("URL {0} contains no data"),
   field_5361("{0} values have been added before statistic is configured"),
   field_5531("vector length mismatch: got {0} but expected {1}"),
   field_5566("vector must have at least one element"),
   field_5391("weigth array must contain at least one non-zero value"),
   field_5443("wrong array shape (block length = {0}, expected {1})"),
   field_5562("{0} points are required, got only {1}"),
   field_5612("number of points ({0})"),
   field_5364("denominator must be different from 0"),
   field_5520("zero denominator in fraction {0}/{1}"),
   field_5538("the fraction to divide by must not be zero: {0}/{1}"),
   field_5363("zero norm"),
   field_5430("zero norm for rotation axis"),
   field_5627("zero norm for rotation defining vector"),
   field_5556("zero not allowed here");

   private final String field_5595;

   private class_1023(String var3) {
      this.field_5595 = var3;
   }

   public String 펊躚뗴贞ᢻⰛ() {
      return this.field_5595;
   }

   public String ᜄ㐈䢶㦖綋堧(Locale var1) {
      try {
         String var4 = class_1023.class.getName().replaceAll("\\.", "/");
         ResourceBundle var5 = ResourceBundle.getBundle("assets/" + var4, var1);
         if (var5.getLocale().getLanguage().equals(var1.getLanguage())) {
            return var5.getString(this.toString());
         }
      } catch (MissingResourceException var6) {
      }

      return this.field_5595;
   }
}
