package net.minecraft.world.biome;

import mapped.RegistryKey;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.registry.Registry;

public abstract class Biomes {
   public static final RegistryKey<Biome> OCEAN = makeKey("ocean");
   public static final RegistryKey<Biome> PLAINS = makeKey("plains");
   public static final RegistryKey<Biome> DESERT = makeKey("desert");
   public static final RegistryKey<Biome> MOUNTAINS = makeKey("mountains");
   public static final RegistryKey<Biome> FOREST = makeKey("forest");
   public static final RegistryKey<Biome> TAIGA = makeKey("taiga");
   public static final RegistryKey<Biome> SWAMP = makeKey("swamp");
   public static final RegistryKey<Biome> RIVER = makeKey("river");
   public static final RegistryKey<Biome> NETHER_WASTES = makeKey("nether_wastes");
   public static final RegistryKey<Biome> THE_END = makeKey("the_end");
   public static final RegistryKey<Biome> FROZEN_OCEAN = makeKey("frozen_ocean");
   public static final RegistryKey<Biome> FROZEN_RIVER = makeKey("frozen_river");
   public static final RegistryKey<Biome> SNOWY_TUNDRA = makeKey("snowy_tundra");
   public static final RegistryKey<Biome> SNOWY_MOUNTAINS = makeKey("snowy_mountains");
   public static final RegistryKey<Biome> MUSHROOM_FIELDS = makeKey("mushroom_fields");
   public static final RegistryKey<Biome> MUSHROOM_FIELD_SHORE = makeKey("mushroom_field_shore");
   public static final RegistryKey<Biome> BEACH = makeKey("beach");
   public static final RegistryKey<Biome> DESERT_HILLS = makeKey("desert_hills");
   public static final RegistryKey<Biome> WOODED_HILLS = makeKey("wooded_hills");
   public static final RegistryKey<Biome> TAIGA_HILLS = makeKey("taiga_hills");
   public static final RegistryKey<Biome> MOUNTAIN_EDGE = makeKey("mountain_edge");
   public static final RegistryKey<Biome> JUNGLE = makeKey("jungle");
   public static final RegistryKey<Biome> JUNGLE_HILLS = makeKey("jungle_hills");
   public static final RegistryKey<Biome> JUNGLE_EDGE = makeKey("jungle_edge");
   public static final RegistryKey<Biome> DEEP_OCEAN = makeKey("deep_ocean");
   public static final RegistryKey<Biome> STONE_SHORE = makeKey("stone_shore");
   public static final RegistryKey<Biome> SNOWY_BEACH = makeKey("snowy_beach");
   public static final RegistryKey<Biome> BIRCH_FOREST = makeKey("birch_forest");
   public static final RegistryKey<Biome> BIRCH_FOREST_HILLS = makeKey("birch_forest_hills");
   public static final RegistryKey<Biome> DARK_FOREST = makeKey("dark_forest");
   public static final RegistryKey<Biome> SNOWY_TAIGA = makeKey("snowy_taiga");
   public static final RegistryKey<Biome> SNOWY_TAIGA_HILLS = makeKey("snowy_taiga_hills");
   public static final RegistryKey<Biome> GIANT_TREE_TAIGA = makeKey("giant_tree_taiga");
   public static final RegistryKey<Biome> GIANT_TREE_TAIGA_HILLS = makeKey("giant_tree_taiga_hills");
   public static final RegistryKey<Biome> WOODED_MOUNTAINS = makeKey("wooded_mountains");
   public static final RegistryKey<Biome> SAVANNA = makeKey("savanna");
   public static final RegistryKey<Biome> SAVANNA_PLATEAU = makeKey("savanna_plateau");
   public static final RegistryKey<Biome> BADLANDS = makeKey("badlands");
   public static final RegistryKey<Biome> WOODED_BADLANDS_PLATEAU = makeKey("wooded_badlands_plateau");
   public static final RegistryKey<Biome> BADLANDS_PLATEAU = makeKey("badlands_plateau");
   public static final RegistryKey<Biome> field44161 = makeKey("small_end_islands");
   public static final RegistryKey<Biome> field44162 = makeKey("end_midlands");
   public static final RegistryKey<Biome> field44163 = makeKey("end_highlands");
   public static final RegistryKey<Biome> field44164 = makeKey("end_barrens");
   public static final RegistryKey<Biome> field44165 = makeKey("warm_ocean");
   public static final RegistryKey<Biome> field44166 = makeKey("lukewarm_ocean");
   public static final RegistryKey<Biome> field44167 = makeKey("cold_ocean");
   public static final RegistryKey<Biome> field44168 = makeKey("deep_warm_ocean");
   public static final RegistryKey<Biome> field44169 = makeKey("deep_lukewarm_ocean");
   public static final RegistryKey<Biome> field44170 = makeKey("deep_cold_ocean");
   public static final RegistryKey<Biome> field44171 = makeKey("deep_frozen_ocean");
   public static final RegistryKey<Biome> field44172 = makeKey("the_void");
   public static final RegistryKey<Biome> field44173 = makeKey("sunflower_plains");
   public static final RegistryKey<Biome> field44174 = makeKey("desert_lakes");
   public static final RegistryKey<Biome> field44175 = makeKey("gravelly_mountains");
   public static final RegistryKey<Biome> field44176 = makeKey("flower_forest");
   public static final RegistryKey<Biome> TAIGA_MOUNTAINS = makeKey("taiga_mountains");
   public static final RegistryKey<Biome> SWAMP_HILLS = makeKey("swamp_hills");
   public static final RegistryKey<Biome> ICE_SPIKES = makeKey("ice_spikes");
   public static final RegistryKey<Biome> field44180 = makeKey("modified_jungle");
   public static final RegistryKey<Biome> field44181 = makeKey("modified_jungle_edge");
   public static final RegistryKey<Biome> field44182 = makeKey("tall_birch_forest");
   public static final RegistryKey<Biome> field44183 = makeKey("tall_birch_hills");
   public static final RegistryKey<Biome> field44184 = makeKey("dark_forest_hills");
   public static final RegistryKey<Biome> field44185 = makeKey("snowy_taiga_mountains");
   public static final RegistryKey<Biome> field44186 = makeKey("giant_spruce_taiga");
   public static final RegistryKey<Biome> field44187 = makeKey("giant_spruce_taiga_hills");
   public static final RegistryKey<Biome> field44188 = makeKey("modified_gravelly_mountains");
   public static final RegistryKey<Biome> field44189 = makeKey("shattered_savanna");
   public static final RegistryKey<Biome> field44190 = makeKey("shattered_savanna_plateau");
   public static final RegistryKey<Biome> field44191 = makeKey("eroded_badlands");
   public static final RegistryKey<Biome> field44192 = makeKey("modified_wooded_badlands_plateau");
   public static final RegistryKey<Biome> field44193 = makeKey("modified_badlands_plateau");
   public static final RegistryKey<Biome> field44194 = makeKey("bamboo_jungle");
   public static final RegistryKey<Biome> field44195 = makeKey("bamboo_jungle_hills");
   public static final RegistryKey<Biome> field44196 = makeKey("soul_sand_valley");
   public static final RegistryKey<Biome> field44197 = makeKey("crimson_forest");
   public static final RegistryKey<Biome> field44198 = makeKey("warped_forest");
   public static final RegistryKey<Biome> field44199 = makeKey("basalt_deltas");

   private static RegistryKey<Biome> makeKey(String var0) {
      return RegistryKey.<Biome>getOrCreateKey(Registry.BIOME_KEY, new ResourceLocation(var0));
   }
}
