package net.minecraft.state.properties;

import net.minecraft.block.WallHeight;
import net.minecraft.state.BooleanProperty;
import net.minecraft.state.DirectionProperty;
import net.minecraft.state.EnumProperty;
import net.minecraft.state.IntegerProperty;
import net.minecraft.util.Direction;
import net.minecraft.world.gen.feature.jigsaw.JigsawOrientation;

public class BlockStateProperties {
   public static final BooleanProperty field39682 = BooleanProperty.create("attached");
   public static final BooleanProperty field39683 = BooleanProperty.create("bottom");
   public static final BooleanProperty field39684 = BooleanProperty.create("conditional");
   public static final BooleanProperty field39685 = BooleanProperty.create("disarmed");
   public static final BooleanProperty field39686 = BooleanProperty.create("drag");
   public static final BooleanProperty field39687 = BooleanProperty.create("enabled");
   public static final BooleanProperty field39688 = BooleanProperty.create("extended");
   public static final BooleanProperty field39689 = BooleanProperty.create("eye");
   public static final BooleanProperty field39690 = BooleanProperty.create("falling");
   public static final BooleanProperty field39691 = BooleanProperty.create("hanging");
   public static final BooleanProperty field39692 = BooleanProperty.create("has_bottle_0");
   public static final BooleanProperty field39693 = BooleanProperty.create("has_bottle_1");
   public static final BooleanProperty field39694 = BooleanProperty.create("has_bottle_2");
   public static final BooleanProperty field39695 = BooleanProperty.create("has_record");
   public static final BooleanProperty field39696 = BooleanProperty.create("has_book");
   public static final BooleanProperty field39697 = BooleanProperty.create("inverted");
   public static final BooleanProperty IN_WALL = BooleanProperty.create("in_wall");
   public static final BooleanProperty field39699 = BooleanProperty.create("lit");
   public static final BooleanProperty field39700 = BooleanProperty.create("locked");
   public static final BooleanProperty field39701 = BooleanProperty.create("occupied");
   public static final BooleanProperty OPEN = BooleanProperty.create("open");
   public static final BooleanProperty field39703 = BooleanProperty.create("persistent");
   public static final BooleanProperty POWERED = BooleanProperty.create("powered");
   public static final BooleanProperty field39705 = BooleanProperty.create("short");
   public static final BooleanProperty field39706 = BooleanProperty.create("signal_fire");
   public static final BooleanProperty field39707 = BooleanProperty.create("snowy");
   public static final BooleanProperty field39708 = BooleanProperty.create("triggered");
   public static final BooleanProperty field39709 = BooleanProperty.create("unstable");
   public static final BooleanProperty WATERLOGGED = BooleanProperty.create("waterlogged");
   public static final BooleanProperty field39711 = BooleanProperty.create("vine_end");
   public static final EnumProperty<Direction.Axis> field39712 = EnumProperty.<Direction.Axis>method30483("axis", Direction.Axis.class, Direction.Axis.X, Direction.Axis.Z);
   public static final EnumProperty<Direction.Axis> field39713 = EnumProperty.<Direction.Axis>create("axis", Direction.Axis.class);
   public static final BooleanProperty field39714 = BooleanProperty.create("up");
   public static final BooleanProperty field39715 = BooleanProperty.create("down");
   public static final BooleanProperty field39716 = BooleanProperty.create("north");
   public static final BooleanProperty field39717 = BooleanProperty.create("east");
   public static final BooleanProperty field39718 = BooleanProperty.create("south");
   public static final BooleanProperty field39719 = BooleanProperty.create("west");
   public static final DirectionProperty FACING = DirectionProperty.method30486(
      "facing", Direction.NORTH, Direction.EAST, Direction.SOUTH, Direction.WEST, Direction.UP, Direction.DOWN
   );
   public static final DirectionProperty FACING_EXCEPT_UP = DirectionProperty.create("facing", var0 -> var0 != Direction.UP);
   public static final DirectionProperty HORIZONTAL_FACING = DirectionProperty.create("facing", Direction.Plane.HORIZONTAL);
   public static final EnumProperty<JigsawOrientation> ORIENTATION = EnumProperty.<JigsawOrientation>create("orientation", JigsawOrientation.class);
   public static final EnumProperty<AttachFace> FACE = EnumProperty.<AttachFace>create("face", AttachFace.class);
   public static final EnumProperty<BellAttachment> BELL_ATTACHMENT = EnumProperty.<BellAttachment>create("attachment", BellAttachment.class);
   public static final EnumProperty<WallHeight> field39726 = EnumProperty.<WallHeight>create("east", WallHeight.class);
   public static final EnumProperty<WallHeight> field39727 = EnumProperty.<WallHeight>create("north", WallHeight.class);
   public static final EnumProperty<WallHeight> field39728 = EnumProperty.<WallHeight>create("south", WallHeight.class);
   public static final EnumProperty<WallHeight> field39729 = EnumProperty.<WallHeight>create("west", WallHeight.class);
   public static final EnumProperty<RedstoneSide> field39730 = EnumProperty.<RedstoneSide>create("east", RedstoneSide.class);
   public static final EnumProperty<RedstoneSide> field39731 = EnumProperty.<RedstoneSide>create("north", RedstoneSide.class);
   public static final EnumProperty<RedstoneSide> field39732 = EnumProperty.<RedstoneSide>create("south", RedstoneSide.class);
   public static final EnumProperty<RedstoneSide> field39733 = EnumProperty.<RedstoneSide>create("west", RedstoneSide.class);
   public static final EnumProperty<DoubleBlockHalf> DOUBLE_BLOCK_HALF = EnumProperty.<DoubleBlockHalf>create("half", DoubleBlockHalf.class);
   public static final EnumProperty<Half> HALF = EnumProperty.<Half>create("half", Half.class);
   public static final EnumProperty<RailShape> field39736 = EnumProperty.<RailShape>create("shape", RailShape.class);
   public static final EnumProperty<RailShape> field39737 = EnumProperty.<RailShape>method30482(
      "shape", RailShape.class, var0 -> var0 != RailShape.field256 && var0 != RailShape.field255 && var0 != RailShape.field253 && var0 != RailShape.field254
   );
   public static final IntegerProperty field39738 = IntegerProperty.create("age", 0, 1);
   public static final IntegerProperty field39739 = IntegerProperty.create("age", 0, 2);
   public static final IntegerProperty field39740 = IntegerProperty.create("age", 0, 3);
   public static final IntegerProperty field39741 = IntegerProperty.create("age", 0, 5);
   public static final IntegerProperty field39742 = IntegerProperty.create("age", 0, 7);
   public static final IntegerProperty field39743 = IntegerProperty.create("age", 0, 15);
   public static final IntegerProperty field39744 = IntegerProperty.create("age", 0, 25);
   public static final IntegerProperty field39745 = IntegerProperty.create("bites", 0, 6);
   public static final IntegerProperty field39746 = IntegerProperty.create("delay", 1, 4);
   public static final IntegerProperty field39747 = IntegerProperty.create("distance", 1, 7);
   public static final IntegerProperty field39748 = IntegerProperty.create("eggs", 1, 4);
   public static final IntegerProperty field39749 = IntegerProperty.create("hatch", 0, 2);
   public static final IntegerProperty field39750 = IntegerProperty.create("layers", 1, 8);
   public static final IntegerProperty field39751 = IntegerProperty.create("level", 0, 3);
   public static final IntegerProperty field39752 = IntegerProperty.create("level", 0, 8);
   public static final IntegerProperty field39753 = IntegerProperty.create("level", 1, 8);
   public static final IntegerProperty field39754 = IntegerProperty.create("honey_level", 0, 5);
   public static final IntegerProperty field39755 = IntegerProperty.create("level", 0, 15);
   public static final IntegerProperty field39756 = IntegerProperty.create("moisture", 0, 7);
   public static final IntegerProperty field39757 = IntegerProperty.create("note", 0, 24);
   public static final IntegerProperty field39758 = IntegerProperty.create("pickles", 1, 4);
   public static final IntegerProperty field39759 = IntegerProperty.create("power", 0, 15);
   public static final IntegerProperty field39760 = IntegerProperty.create("stage", 0, 1);
   public static final IntegerProperty field39761 = IntegerProperty.create("distance", 0, 7);
   public static final IntegerProperty field39762 = IntegerProperty.create("charges", 0, 4);
   public static final IntegerProperty field39763 = IntegerProperty.create("rotation", 0, 15);
   public static final EnumProperty<BedPart> field39764 = EnumProperty.<BedPart>create("part", BedPart.class);
   public static final EnumProperty<ChestType> field39765 = EnumProperty.<ChestType>create("type", ChestType.class);
   public static final EnumProperty<ComparatorMode> field39766 = EnumProperty.<ComparatorMode>create("mode", ComparatorMode.class);
   public static final EnumProperty<DoorHingeSide> DOOR_HINGE = EnumProperty.<DoorHingeSide>create("hinge", DoorHingeSide.class);
   public static final EnumProperty<NoteBlockInstrument> field39768 = EnumProperty.<NoteBlockInstrument>create("instrument", NoteBlockInstrument.class);
   public static final EnumProperty<PistonType> field39769 = EnumProperty.<PistonType>create("type", PistonType.class);
   public static final EnumProperty<SlabType> field39770 = EnumProperty.<SlabType>create("type", SlabType.class);
   public static final EnumProperty<StairsShape> STAIRS_SHAPE = EnumProperty.<StairsShape>create("shape", StairsShape.class);
   public static final EnumProperty<StructureMode> field39772 = EnumProperty.<StructureMode>create("mode", StructureMode.class);
   public static final EnumProperty<BambooLeaves> field39773 = EnumProperty.<BambooLeaves>create("leaves", BambooLeaves.class);
}
