package mapped;

import org.lwjgl.opengl.ARBShaderObjects;

public class Class7874 {
   public int field33740;
   public int field33741;
   public int field33742;
   public int field33743;
   public int field33744;
   public int field33745;
   public int field33746;
   public int field33747;
   public int field33748;
   public int field33749;
   public int field33750;
   public int field33751;
   public int field33752;
   public int field33753;
   public int field33754;
   public int field33755;
   public int field33756;
   public int field33757;
   public int field33758;
   public int field33759;
   public int field33760;
   public int field33761;
   public int field33762;
   public int field33763;
   public int field33764;
   public int field33765;
   public int field33766;
   public int field33767;
   public int field33768;
   public int field33769;
   public int field33770;
   public int field33771;
   public int field33772;
   public int field33773;
   public int field33774;
   public int field33775;
   public int field33776;
   public int field33777;
   public int field33778;
   public int field33779;
   public int field33780;
   public int field33781;
   public int field33782;
   public int field33783;
   public int field33784;
   public int field33785;
   public int field33786;
   public int field33787;
   public int field33788;
   public int field33789;
   public int field33790;
   public int field33791;
   public int field33792;
   public int field33793;
   public int field33794;
   public int field33795;
   public int field33796;
   public int field33797;
   public int field33798;
   public int field33799;
   public int field33800;
   public int field33801;
   public int field33802;
   public int field33803;
   public int field33804;
   public int field33805;
   public int field33806;
   public int field33807;
   public int field33808;
   public int field33809;
   public int field33810;
   public int field33811;
   public int field33812;
   public int field33813;
   public int field33814;

   public Class7874(int var1) {
      this.field33740 = var1;
      this.field33741 = ARBShaderObjects.glGetUniformLocationARB(var1, "texture");
      this.field33742 = ARBShaderObjects.glGetUniformLocationARB(var1, "lightmap");
      this.field33743 = ARBShaderObjects.glGetUniformLocationARB(var1, "normals");
      this.field33744 = ARBShaderObjects.glGetUniformLocationARB(var1, "specular");
      this.field33745 = ARBShaderObjects.glGetUniformLocationARB(var1, "shadow");
      this.field33746 = ARBShaderObjects.glGetUniformLocationARB(var1, "watershadow");
      this.field33747 = ARBShaderObjects.glGetUniformLocationARB(var1, "shadowtex0");
      this.field33748 = ARBShaderObjects.glGetUniformLocationARB(var1, "shadowtex1");
      this.field33749 = ARBShaderObjects.glGetUniformLocationARB(var1, "depthtex0");
      this.field33750 = ARBShaderObjects.glGetUniformLocationARB(var1, "depthtex1");
      this.field33751 = ARBShaderObjects.glGetUniformLocationARB(var1, "shadowcolor");
      this.field33752 = ARBShaderObjects.glGetUniformLocationARB(var1, "shadowcolor0");
      this.field33753 = ARBShaderObjects.glGetUniformLocationARB(var1, "shadowcolor1");
      this.field33754 = ARBShaderObjects.glGetUniformLocationARB(var1, "noisetex");
      this.field33755 = ARBShaderObjects.glGetUniformLocationARB(var1, "gcolor");
      this.field33756 = ARBShaderObjects.glGetUniformLocationARB(var1, "gdepth");
      this.field33757 = ARBShaderObjects.glGetUniformLocationARB(var1, "gnormal");
      this.field33758 = ARBShaderObjects.glGetUniformLocationARB(var1, "composite");
      this.field33759 = ARBShaderObjects.glGetUniformLocationARB(var1, "gaux1");
      this.field33760 = ARBShaderObjects.glGetUniformLocationARB(var1, "gaux2");
      this.field33761 = ARBShaderObjects.glGetUniformLocationARB(var1, "gaux3");
      this.field33762 = ARBShaderObjects.glGetUniformLocationARB(var1, "gaux4");
      this.field33763 = ARBShaderObjects.glGetUniformLocationARB(var1, "colortex0");
      this.field33764 = ARBShaderObjects.glGetUniformLocationARB(var1, "colortex1");
      this.field33765 = ARBShaderObjects.glGetUniformLocationARB(var1, "colortex2");
      this.field33766 = ARBShaderObjects.glGetUniformLocationARB(var1, "colortex3");
      this.field33767 = ARBShaderObjects.glGetUniformLocationARB(var1, "colortex4");
      this.field33768 = ARBShaderObjects.glGetUniformLocationARB(var1, "colortex5");
      this.field33769 = ARBShaderObjects.glGetUniformLocationARB(var1, "colortex6");
      this.field33770 = ARBShaderObjects.glGetUniformLocationARB(var1, "colortex7");
      this.field33771 = ARBShaderObjects.glGetUniformLocationARB(var1, "gdepthtex");
      this.field33772 = ARBShaderObjects.glGetUniformLocationARB(var1, "depthtex2");
      this.field33773 = ARBShaderObjects.glGetUniformLocationARB(var1, "tex");
      this.field33774 = ARBShaderObjects.glGetUniformLocationARB(var1, "heldItemId");
      this.field33775 = ARBShaderObjects.glGetUniformLocationARB(var1, "heldBlockLightValue");
      this.field33776 = ARBShaderObjects.glGetUniformLocationARB(var1, "fogMode");
      this.field33777 = ARBShaderObjects.glGetUniformLocationARB(var1, "fogColor");
      this.field33778 = ARBShaderObjects.glGetUniformLocationARB(var1, "skyColor");
      this.field33779 = ARBShaderObjects.glGetUniformLocationARB(var1, "worldTime");
      this.field33780 = ARBShaderObjects.glGetUniformLocationARB(var1, "moonPhase");
      this.field33781 = ARBShaderObjects.glGetUniformLocationARB(var1, "frameTimeCounter");
      this.field33782 = ARBShaderObjects.glGetUniformLocationARB(var1, "sunAngle");
      this.field33783 = ARBShaderObjects.glGetUniformLocationARB(var1, "shadowAngle");
      this.field33784 = ARBShaderObjects.glGetUniformLocationARB(var1, "rainStrength");
      this.field33785 = ARBShaderObjects.glGetUniformLocationARB(var1, "aspectRatio");
      this.field33786 = ARBShaderObjects.glGetUniformLocationARB(var1, "viewWidth");
      this.field33787 = ARBShaderObjects.glGetUniformLocationARB(var1, "viewHeight");
      this.field33788 = ARBShaderObjects.glGetUniformLocationARB(var1, "near");
      this.field33789 = ARBShaderObjects.glGetUniformLocationARB(var1, "far");
      this.field33790 = ARBShaderObjects.glGetUniformLocationARB(var1, "sunPosition");
      this.field33791 = ARBShaderObjects.glGetUniformLocationARB(var1, "moonPosition");
      this.field33792 = ARBShaderObjects.glGetUniformLocationARB(var1, "upPosition");
      this.field33793 = ARBShaderObjects.glGetUniformLocationARB(var1, "previousCameraPosition");
      this.field33794 = ARBShaderObjects.glGetUniformLocationARB(var1, "cameraPosition");
      this.field33795 = ARBShaderObjects.glGetUniformLocationARB(var1, "gbufferModelView");
      this.field33796 = ARBShaderObjects.glGetUniformLocationARB(var1, "gbufferModelViewInverse");
      this.field33797 = ARBShaderObjects.glGetUniformLocationARB(var1, "gbufferPreviousProjection");
      this.field33798 = ARBShaderObjects.glGetUniformLocationARB(var1, "gbufferProjection");
      this.field33799 = ARBShaderObjects.glGetUniformLocationARB(var1, "gbufferProjectionInverse");
      this.field33800 = ARBShaderObjects.glGetUniformLocationARB(var1, "gbufferPreviousModelView");
      this.field33801 = ARBShaderObjects.glGetUniformLocationARB(var1, "shadowProjection");
      this.field33802 = ARBShaderObjects.glGetUniformLocationARB(var1, "shadowProjectionInverse");
      this.field33803 = ARBShaderObjects.glGetUniformLocationARB(var1, "shadowModelView");
      this.field33804 = ARBShaderObjects.glGetUniformLocationARB(var1, "shadowModelViewInverse");
      this.field33805 = ARBShaderObjects.glGetUniformLocationARB(var1, "wetness");
      this.field33806 = ARBShaderObjects.glGetUniformLocationARB(var1, "eyeAltitude");
      this.field33807 = ARBShaderObjects.glGetUniformLocationARB(var1, "eyeBrightness");
      this.field33808 = ARBShaderObjects.glGetUniformLocationARB(var1, "eyeBrightnessSmooth");
      this.field33809 = ARBShaderObjects.glGetUniformLocationARB(var1, "terrainTextureSize");
      this.field33810 = ARBShaderObjects.glGetUniformLocationARB(var1, "terrainIconSize");
      this.field33811 = ARBShaderObjects.glGetUniformLocationARB(var1, "isEyeInWater");
      this.field33812 = ARBShaderObjects.glGetUniformLocationARB(var1, "hideGUI");
      this.field33813 = ARBShaderObjects.glGetUniformLocationARB(var1, "centerDepthSmooth");
      this.field33814 = ARBShaderObjects.glGetUniformLocationARB(var1, "atlasSize");
   }
}
