// 
// Decompiled by Procyon v0.6.0
// 

package mapped;

import java.util.MissingResourceException;
import java.util.ResourceBundle;
import java.util.Locale;

public enum Class2189 implements Class2190
{
    field12997("Argument {0} outside domain [{1} ; {2}]"), 
    field12998("array size cannot be greater than {0}"), 
    field12999("array sizes should have difference 1 ({0} != {1} + 1)"), 
    field13000("array sums to zero"), 
    field13001("eigen decomposition of assymetric matrices not supported yet"), 
    field13002("matrix must have at least one column"), 
    field13003("matrix must have at least one row"), 
    field13004("bandwidth ({0})"), 
    field13005("Bessel function of order {0} cannot be computed for x = {1}"), 
    field13006("Bessel function of order {0} failed to converge for x = {1}"), 
    field13007("must have n >= k for binomial coefficient (n, k), got k = {0}, n = {1}"), 
    field13008("must have n >= 0 for binomial coefficient (n, k), got n = {0}"), 
    field13009("statistics constructed from external moments cannot be cleared"), 
    field13010("cannot compute 0-th root of unity, indefinite result"), 
    field13011("cannot compute beta density at 0 when alpha = {0,number}"), 
    field13012("cannot compute beta density at 1 when beta = %.3g"), 
    field13013("cannot compute nth root for null or negative n: {0}"), 
    field13014("cannot discard a negative number of elements ({0})"), 
    field13015("cannot format a {0} instance as a 3D vector"), 
    field13016("cannot format a {0} instance as a complex number"), 
    field13017("cannot format a {0} instance as a real vector"), 
    field13018("cannot format given object as a fraction number"), 
    field13019("statistics constructed from external moments cannot be incremented"), 
    field13020("cannot normalize a zero norm vector"), 
    field13021("elements cannot be retrieved from a negative array index {0}"), 
    field13022("cannot set an element at a negative index {0}"), 
    field13023("cannot substitute an element from an empty array"), 
    field13024("Conversion Exception in Transformation: {0}"), 
    field13025("Cardan angles singularity"), 
    field13026("class ({0}) does not implement Comparable"), 
    field13027("too close vertices near point ({0}, {1}, {2})"), 
    field13028("the closest orthogonal matrix has a negative determinant {0}"), 
    field13029("column index {0} out of allowed range [{1}, {2}]"), 
    field13030("column index ({0})"), 
    field13031("constraint"), 
    field13032("Continued fraction convergents diverged to +/- infinity for value {0}"), 
    field13033("Continued fraction diverged to NaN for value {0}"), 
    field13034("contraction criteria ({0}) smaller than the expansion factor ({1}).  This would lead to a never ending loop of expansion and contraction as a newly expanded internal storage array would immediately satisfy the criteria for contraction."), 
    field13035("contraction criteria smaller than one ({0}).  This would lead to a never ending loop of expansion and contraction as an internal storage array length equal to the number of elements would satisfy the contraction criteria."), 
    field13036("convergence failed"), 
    field13037("some outline boundary loops cross each other"), 
    field13038("crossover rate ({0})"), 
    field13039("Cumulative probability function returned NaN for argument {0} p = {1}"), 
    field13040("some rows have length {0} while others have length {1}"), 
    field13041("original and permuted data must contain the same elements"), 
    field13042("digest not initialized"), 
    field13043("got {0}x{1} but expected {2}x{3}"), 
    field13044("{0} != {1}"), 
    field13045("dimensions mismatch"), 
    field13046("Discrete cumulative probability function returned NaN for argument {0}"), 
    field13047("distribution not loaded"), 
    field13048("duplicated abscissa {0} causes division by zero"), 
    field13049("edge joining points ({0}, {1}, {2}) and ({3}, {4}, {5}) is connected to one facet only"), 
    field13050("elitism rate ({0})"), 
    field13051("empty cluster in k-means"), 
    field13052("sample for interpolation is empty"), 
    field13053("empty polynomials coefficients array"), 
    field13054("empty selected column index array"), 
    field13055("empty selected row index array"), 
    field13056("empty string for imaginary character"), 
    field13057("endpoints do not specify an interval: [{0}, {1}]"), 
    field13058("equal vertices {0} and {1} in simplex configuration"), 
    field13059("Euler angles singularity"), 
    field13060("evaluation"), 
    field13061("expansion factor smaller than one ({0})"), 
    field13062("facets orientation mismatch around edge joining points ({0}, {1}, {2}) and ({3}, {4}, {5})"), 
    field13063("must have n >= 0 for n!, got n = {0}"), 
    field13064("number of iterations={4}, maximum iterations={5}, initial={6}, lower bound={7}, upper bound={8}, final a value={0}, final b value={1}, f(a)={2}, f(b)={3}"), 
    field13065("Unable to convert {0} to fraction after {1} iterations"), 
    field13066("first {0} columns are not initialized yet"), 
    field13067("first element is not 0: {0}"), 
    field13068("first {0} rows are not initialized yet"), 
    field13069("Overflow trying to convert {0} to fraction ({1}/{2})"), 
    field13070("function is not differentiable"), 
    field13071("function is not polynomial"), 
    field13072("overflow: gcd({0}, {1}) is 2^31"), 
    field13073("overflow: gcd({0}, {1}) is 2^63"), 
    field13074("{0} wide hole between models time ranges"), 
    field13075("condition number {1} is too high "), 
    field13076("inconsistent state at 2\u03c0 wrapping"), 
    field13077("the index specified: {0} is larger than the current maximal index {1}"), 
    field13078("index ({0}) is not positive"), 
    field13079("index {0} out of allowed range [{1}, {2}]"), 
    field13080("index ({0})"), 
    field13081("{0} is not a finite number"), 
    field13082("interval bounds must be finite"), 
    field13083("value {0} at index {1}"), 
    field13084("Array contains an infinite element, {0} at index {1}"), 
    field13085("cannot convert infinite value"), 
    field13086("initial capacity ({0}) is not positive"), 
    field13087("initial column {1} after final column {0}"), 
    field13088("initial row {1} after final row {0}"), 
    @Deprecated
    field13089("input data comes from unsupported datasource: {0}, supported sources: {1}, {2}"), 
    field13090("instance of class {0} not comparable to existing values"), 
    field13091("insufficient data"), 
    field13092("insufficient data for t statistic, needs at least 2, got {0}"), 
    field13093("insufficient dimension {0}, must be at least {1}"), 
    field13094("dimension ({0})"), 
    field13095("sample contains {0} observed points, at least {1} are required"), 
    field13096("insufficient data: only {0} rows and {1} columns."), 
    field13097("multistep method needs at least {0} previous steps, got {1}"), 
    field13098("internal error, please fill a bug report at {0}"), 
    field13099("invalid binary digit: {0}"), 
    field13100("binary mutation works on BinaryChromosome only"), 
    field13101("invalid bracketing parameters:  lower bound={0},  initial={1}, upper bound={2}"), 
    field13102("one-point crossover only works with fixed-length chromosomes"), 
    field13103("required functionality is missing in {0}"), 
    field13104("invalid interval, initial value parameters:  lower={0}, initial={1}, upper={2}"), 
    field13105("invalid iteration limits: min={0}, max={1}"), 
    field13106("bad value for maximum iterations number: {0}"), 
    field13107("the number of observations is not sufficient to conduct regression"), 
    field13108("input data array length = {0} does not match the number of observations = {1} and the number of regressors = {2}"), 
    field13109("length of regressor array = {0} does not match the number of variables = {1} in the model"), 
    field13110("invalid rounding method {0}, valid methods: {1} ({2}), {3} ({4}), {5} ({6}), {7} ({8}), {9} ({10}), {11} ({12}), {13} ({14}), {15} ({16})"), 
    field13111("iterator exhausted"), 
    field13112("iterations"), 
    field13113("overflow: lcm({0}, {1}) is 2^31"), 
    field13114("overflow: lcm({0}, {1}) is 2^63"), 
    field13115("list of chromosomes bigger than maxPopulationSize"), 
    field13116("Loess expects at least 1 point"), 
    field13117("lower bound ({0}) must be strictly less than upper bound ({1})"), 
    field13118("lower endpoint ({0}) must be less than or equal to upper endpoint ({1})"), 
    field13119("map has been modified while iterating"), 
    field13120("evaluations"), 
    field13121("maximal count ({0}) exceeded"), 
    field13122("maximal number of iterations ({0}) exceeded"), 
    field13123("minimal step size ({1,number,0.00E00}) reached, integration needs {0,number,0.00E00}"), 
    field13124("Loess expects the abscissa and ordinate arrays to be of the same size, but got {0} abscissae and {1} ordinatae"), 
    field13125("mutation rate ({0})"), 
    field13126("element {0} is NaN"), 
    field13127("cannot convert NaN value"), 
    field13128("brightness exponent should be positive or null, but got {0}"), 
    field13129("negative complex module {0}"), 
    field13130("element ({0}, {1}) is negative: {2}"), 
    field13131("element {0} is negative: {1}"), 
    field13132("number of successes must be non-negative ({0})"), 
    field13133("number of successes ({0})"), 
    field13134("number of trials must be non-negative ({0})"), 
    field13135("number of interpolation points ({0})"), 
    field13136("number of trials ({0})"), 
    field13137("vertices do not form a convex hull in CCW winding"), 
    field13138("number of robustness iterations ({0})"), 
    field13139("start position ({0})"), 
    field13140("Continued fraction convergents failed to converge (in less than {0} iterations) for value {1}"), 
    field13141("non-invertible affine transform collapses some lines into single points"), 
    field13142("number of microsphere elements must be positive, but got {0}"), 
    field13143("polynomial degree must be positive: degree={0}"), 
    field13144("all abscissae must be finite real numbers, but {0}-th is {1}"), 
    field13145("all ordinatae must be finite real numbers, but {0}-th is {1}"), 
    field13146("all weights must be finite real numbers, but {0}-th is {1}"), 
    field13147("non square ({0}x{1}) matrix"), 
    field13148("Norm ({0})"), 
    field13149("Cannot normalize to an infinite value"), 
    field13150("Cannot normalize to NaN"), 
    field13151("{0}x{1} and {2}x{3} matrices are not addition compatible"), 
    field13152("points {0} and {1} are not decreasing ({2} < {3})"), 
    field13153("points {3} and {2} are not decreasing ({1} < {0})"), 
    field13154("not enough data ({0} rows) for this many predictors ({1} predictors)"), 
    field13155("spline partition must have at least {0} points, got {1}"), 
    field13156("points {0} and {1} are not increasing ({2} > {3})"), 
    field13157("points {3} and {2} are not increasing ({1} > {0})"), 
    field13158("{0}x{1} and {2}x{3} matrices are not multiplication compatible"), 
    field13159("not positive definite matrix"), 
    field13160("not positive definite matrix: diagonal element at ({1},{1}) is smaller than {2} ({0})"), 
    field13161("non positive definite linear operator"), 
    field13162("non self-adjoint linear operator"), 
    field13163("non square ({0}x{1}) linear operator"), 
    field13164("degrees of freedom ({0})"), 
    field13165("degrees of freedom must be positive ({0})"), 
    field13166("element {0} is not positive: {1}"), 
    field13167("invalid exponent {0} (must be positive)"), 
    field13168("number of elements should be positive ({0})"), 
    field13169("base ({0})"), 
    field13170("exponent ({0})"), 
    field13171("length must be positive ({0})"), 
    field13172("length ({0})"), 
    field13173("mean must be positive ({0})"), 
    field13174("mean ({0})"), 
    field13175("number of sample is not positive: {0}"), 
    field13176("number of samples ({0})"), 
    field13177("permutation k ({0}) must be positive"), 
    field13178("permutation size ({0}"), 
    field13179("the Poisson mean must be positive ({0})"), 
    field13180("population size must be positive ({0})"), 
    field13181("population size ({0})"), 
    field13182("invalid row dimension: {0} (must be positive)"), 
    field13183("sample size must be positive ({0})"), 
    field13184("scale must be positive ({0})"), 
    field13185("scale ({0})"), 
    field13186("shape must be positive ({0})"), 
    field13187("shape ({0})"), 
    field13188("standard deviation must be positive ({0})"), 
    field13189("standard deviation ({0})"), 
    field13190("upper bound must be positive ({0})"), 
    field13191("window size must be positive ({0})"), 
    field13192("{0} is not a power of 2"), 
    field13193("{0} is not a power of 2, consider padding for fix"), 
    field13194("{0} is not a power of 2 plus one"), 
    field13195("points {0} and {1} are not strictly decreasing ({2} <= {3})"), 
    field13196("points {3} and {2} are not strictly decreasing ({1} <= {0})"), 
    field13197("knot values must be strictly increasing"), 
    field13198("points {0} and {1} are not strictly increasing ({2} >= {3})"), 
    field13199("points {3} and {2} are not strictly increasing ({1} >= {0})"), 
    field13200("{0}x{1} and {2}x{3} matrices are not subtraction compatible"), 
    field13201("method not supported in dimension {0}"), 
    field13202("not symmetric matrix"), 
    field13203("non symmetric matrix: the difference between entries at ({0},{1}) and ({1},{0}) is larger than {2}"), 
    field13204("no bin selected"), 
    field13205("none of the {0} start points lead to convergence"), 
    field13206("no data"), 
    field13207("no degrees of freedom ({0} measurements, {1} parameters)"), 
    field13208("This distribution does not have a density function implemented"), 
    field13209("no feasible solution"), 
    field13210("no optimum computed yet"), 
    field13211("Regression model must include at least one regressor"), 
    field13212("no result available"), 
    field13213("no entry at indices ({0}, {1}) in a {2}x{3} matrix"), 
    field13214("NaN is not allowed"), 
    field13215("null is not allowed"), 
    field13216("a null or zero length array not allowed"), 
    field13217("covariance matrix"), 
    field13218("denominator"), 
    field13219("denominator format"), 
    field13220("fraction"), 
    field13221("function"), 
    field13222("imaginary format"), 
    field13223("input array"), 
    field13224("numerator"), 
    field13225("numerator format"), 
    field13226("conversion exception in transformation"), 
    field13227("real format"), 
    field13228("whole format"), 
    field13229("{0} is larger than the maximum ({1})"), 
    field13230("{0} is smaller than the minimum ({1})"), 
    field13231("{0} is larger than, or equal to, the maximum ({1})"), 
    field13232("{0} is smaller than, or equal to, the minimum ({1})"), 
    field13233("number of successes ({0}) must be less than or equal to population size ({1})"), 
    field13234("overflow, numerator too large after multiply: {0}"), 
    field13235("{0} points Legendre-Gauss integrator not supported, number of points must be in the {1}-{2} range"), 
    field13236("observed counts are all 0 in observed array {0}"), 
    field13237("observed counts are both zero for entry {0}"), 
    field13238("the difference between the upper and lower bound must be larger than twice the initial trust region radius ({0})"), 
    field13239("out of bounds quantile value: {0}, must be in (0, 100]"), 
    field13240("out of bounds confidence level {0}, must be between {1} and {2}"), 
    field13241("out of bounds significance level {0}, must be between {1} and {2}"), 
    field13242("significance level ({0})"), 
    field13243("the abscissae array must be sorted in a strictly increasing order, but the {0}-th element is {1} whereas {2}-th is {3}"), 
    field13244("point ({0}, {1}, {2}) is out of plane"), 
    field13245("out of range root of unity index {0} (must be in [{1};{2}])"), 
    field13246("out of range"), 
    field13247("{0} out of [{1}, {2}] range"), 
    field13248("{0} out of ({1}, {2}] range"), 
    field13249("{0} out of [{1}, {2}) range"), 
    field13250("an outline boundary loop is open"), 
    field13251("overflow"), 
    field13252("overflow in fraction {0}/{1}, cannot negate"), 
    field13253("overflow in addition: {0} + {1}"), 
    field13254("overflow in subtraction: {0} - {1}"), 
    field13255("overflow in multiplication: {0} * {1}"), 
    field13256("cannot access {0} method in percentile implementation {1}"), 
    field13257("percentile implementation {0} does not support {1}"), 
    field13258("permutation size ({0}) exceeds permuation domain ({1})"), 
    field13259("polynomial"), 
    field13260("number of polynomial interpolants must match the number of segments ({0} != {1} - 1)"), 
    field13261("population limit has to be positive"), 
    field13262("cannot raise an integral value to a negative power ({0}^{1})"), 
    field13263("propagation direction mismatch"), 
    field13264("RandomKeyMutation works only with RandomKeys, not {0}"), 
    field13265("roots of unity have not been computed yet"), 
    field13266("a {0}x{1} matrix cannot be a rotation matrix"), 
    field13267("row index {0} out of allowed range [{1}, {2}]"), 
    field13268("row index ({0})"), 
    field13269("function values at endpoints do not have different signs, endpoints: [{0}, {1}], values: [{2}, {3}]"), 
    field13270("sample size ({0}) exceeds collection size ({1})"), 
    field13271("sample size ({0}) must be less than or equal to population size ({1})"), 
    field13272("simplex must contain at least one point"), 
    field13273("{0}"), 
    field13274("matrix is singular"), 
    field13275("operator is singular"), 
    field13276("subarray ends after array end"), 
    field13277("cutoff singular value is {0}, should be at most {1}"), 
    field13278("tournament arity ({0}) cannot be bigger than population size ({1})"), 
    field13279("cannot discard {0} elements from a {1} elements array"), 
    field13280("too many regressors ({0}) specified, only {1} in the model"), 
    field13281("cost relative tolerance is too small ({0}), no further reduction in the sum of squares is possible"), 
    field13282("too small integration interval: length = {0}"), 
    field13283("orthogonality tolerance is too small ({0}), solution is orthogonal to the jacobian"), 
    field13284("parameters relative tolerance is too small ({0}), no further improvement in the approximate solution is possible"), 
    field13285("trust region step has failed to reduce Q"), 
    field13286("two or more categories required, got {0}"), 
    field13287("two or more values required in each category, one has {0}"), 
    field13288("unable to bracket optimum in line search"), 
    field13289("unable to compute covariances: singular problem"), 
    field13290("unable to first guess the harmonic coefficients"), 
    field13291("unable to orthogonalize matrix in {0} iterations"), 
    field13292("unable to perform Q.R decomposition on the {0}x{1} jacobian matrix"), 
    field13293("unable to solve: singular problem"), 
    field13294("unbounded solution"), 
    field13295("unknown mode {0}, known modes: {1} ({2}), {3} ({4}), {5} ({6}), {7} ({8}), {9} ({10}) and {11} ({12})"), 
    field13296("unknown parameter {0}"), 
    field13297("ode does not match the main ode set in the extended set"), 
    field13298("string \"{0}\" unparseable (from position {1}) as an object of type {2}"), 
    field13299("string \"{0}\" unparseable (from position {1})"), 
    field13300("unparseable 3D vector: \"{0}\""), 
    field13301("unparseable complex number: \"{0}\""), 
    field13302("unparseable real vector: \"{0}\""), 
    field13303("unsupported expansion mode {0}, supported modes are {1} ({2}) and {3} ({4})"), 
    field13304("unsupported operation"), 
    field13305("arithmetic exception"), 
    field13306("illegal state"), 
    field13307("exception generated in user code"), 
    field13308("URL {0} contains no data"), 
    field13309("{0} values have been added before statistic is configured"), 
    field13310("vector length mismatch: got {0} but expected {1}"), 
    field13311("vector must have at least one element"), 
    field13312("weigth array must contain at least one non-zero value"), 
    field13313("wrong array shape (block length = {0}, expected {1})"), 
    field13314("{0} points are required, got only {1}"), 
    field13315("number of points ({0})"), 
    field13316("denominator must be different from 0"), 
    field13317("zero denominator in fraction {0}/{1}"), 
    field13318("the fraction to divide by must not be zero: {0}/{1}"), 
    field13319("zero norm"), 
    field13320("zero norm for rotation axis"), 
    field13321("zero norm for rotation defining vector"), 
    field13322("zero not allowed here");
    
    private final String field13323;
    
    private Class2189(final String field13323) {
        this.field13323 = field13323;
    }
    
    public String method8357() {
        return this.field13323;
    }
    
    public String method8358(final Locale locale) {
        try {
            final ResourceBundle bundle = ResourceBundle.getBundle("assets/" + Class2189.class.getName().replaceAll("\\.", "/"), locale);
            if (bundle.getLocale().getLanguage().equals(locale.getLanguage())) {
                return bundle.getString(this.toString());
            }
        }
        catch (final MissingResourceException ex) {}
        return this.field13323;
    }
}
